
version: '2'

services:
  web:
    build: .
    command: nodemon --exec yarn start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
